### ISSUE TITLE
Mongo::Error::OperationFailure: text search not enabled

### ISSUE THREAD

**Issue by JustinAiken** [kwhrtsk/chef-errbit-server#4]
Almost there, only failing at the bootstrap step now!

```
Recipe: errbit-server::bootstrap
  * execute[rake errbit:bootstrap to create admin user] action run

    ================================================================================
    Error executing action `run` on resource 'execute[rake errbit:bootstrap to create admin user]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of bundle exec rake errbit:bootstrap > /opt/errbit/bootstrap.out ----
    STDOUT:
    STDERR: rake aborted!
    Mongo::Error::OperationFailure: text search not enabled (16633)
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.0.beta/lib/mongo/operation/result.rb:214:in `validate!'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.0.beta/lib/mongo/operation/write/create_index.rb:74:in `block in execute_message'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.0.beta/lib/mongo/server/connection_pool.rb:99:in `with_connection'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.0.beta/lib/mongo/server/context.rb:63:in `with_connection'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.0.beta/lib/mongo/operation/write/create_index.rb:73:in `execute_message'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.0.beta/lib/mongo/operation/write/create_index.rb:62:in `execute'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.0.beta/lib/mongo/index/view.rb:150:in `create_many'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.0.beta/lib/mongo/index/view.rb:125:in `create_one'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0.beta/lib/mongoid/indexable.rb:37:in `block in create_indexes'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0.beta/lib/mongoid/indexable.rb:31:in `each'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0.beta/lib/mongoid/indexable.rb:31:in `create_indexes'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0.beta/lib/mongoid/tasks/database.rb:20:in `block in create_indexes'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0.beta/lib/mongoid/tasks/database.rb:17:in `each'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0.beta/lib/mongoid/tasks/database.rb:17:in `create_indexes'
    /opt/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0.beta/lib/mongoid/tasks/database.rake:8:in `block (3 levels) in <top (required)>'
    /opt/errbit/releases/20150921144758/lib/tasks/errbit/bootstrap.rake:8:in `block (2 levels) in <top (required)>'
    Tasks: TOP => db:mongoid:create_indexes
    (See full trace by running task with --trace)
    ---- End output of bundle exec rake errbit:bootstrap > /opt/errbit/bootstrap.out ----
    Ran bundle exec rake errbit:bootstrap > /opt/errbit/bootstrap.out returned 1

    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks-2/errbit-server/recipes/bootstrap.rb

     15: execute "rake errbit:bootstrap to create admin user" do
     16:   command "bundle exec rake errbit:bootstrap > /opt/errbit/bootstrap.out"
     17:   cwd "/opt/errbit/current"
     18:    environment _environment
     19:   creates "/opt/errbit/bootstrap.out"
     20: end

    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks-2/errbit-server/recipes/bootstrap.rb:15:in `from_file'

    execute("rake errbit:bootstrap to create admin user") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "bundle exec rake errbit:bootstrap > /opt/errbit/bootstrap.out"
      backup 5
      creates "/opt/errbit/bootstrap.out"
      cwd "/opt/errbit/current"
      environment {"PORT"=>"3000", "RAILS_ENV"=>"production", "UNICORN_PID"=>"/opt/errbit/shared/pids/unicorn.pid", "ERRBIT_HOST"=>"errbit.example.com", "ERRBIT_PROTOCOL"=>"http", "ERRBIT_ENFORCE_SSL"=>"false", "CONFIRM_RESOLVE_ERR"=>"true", "ERRBIT_CONFIRM_ERR_ACTIONS"=>"true", "ERRBIT_USER_HAS_USERNAME"=>"false", "ERRBIT_USE_GRAVATAR"=>"true", "ERRBIT_GRAVATAR_DEFAULT"=>"identicon", "ALLOW_COMMENTS_WITH_ISSUE_TRACKER"=>"true", "SERVE_STATIC_ASSETS"=>"true", "SECRET_KEY_BASE"=>"f258ed69266dc8ad0ca79363c3d2f945c388a9c5920fc9a1ae99a98fbb619f135001c6434849b625884a9405a60cd3d50fc3e3b07ecd38cbed7406a4fccdb59c", "ERRBIT_EMAIL_FROM"=>"errbit@example.com", "ERRBIT_EMAIL_AT_NOTICES"=>"[0]", "ERRBIT_PER_APP_EMAIL_AT_NOTICES"=>"false", "ERRBIT_NOTIFY_AT_NOTICES"=>"[1,10,100]", "ERRBIT_PER_APP_NOTIFY_AT_NOTICES"=>"false", "MONGO_URL"=>"mongodb://localhost", "GITHUB_URL"=>"https://github.com", "GITHUB_AUTHENTICATION"=>"true", "GITHUB_ACCESS_SCOPE"=>"[repo]", "DEVISE_MODULES"=>"[database_authenticatable,recoverable,rememberable,trackable,validatable,omniauthable]", "RBENV_VERSION"=>"2.2.2"}
      returns 0
      declared_type :execute
      cookbook_name :"errbit-server"
      recipe_name "bootstrap"
    end
```

**Comment by kwhrtsk** [comment]
Ummm...I cannot reproduce this error. I tried both of `d533719` and `f1937f69` referenced by #3.
Can you tell me more about your environment and chef parameters?
In particular about the follows:
- Distribution and version(tested only CentOS 6.7 and Ubuntu 14.10)
- MongoDB version(CentOS: `yum info mongodb` / Ubuntu: `apt-cache policy mongodb`)
- Errbit revision(if you specified)

Or could you try [this sample](https://github.com/kwhrtsk/chef-errbit-server/tree/master/sample) and confirm whether same error occurs?

**Comment by JustinAiken** [comment]
Ubuntu 14.10

``` bash
root@errbit:/etc/monit/conf.d# sudo apt-cache policy mongodb
mongodb:
  Installed: 1:2.4.9-1ubuntu2
  Candidate: 1:2.4.9-1ubuntu2
  Version table:
 *** 1:2.4.9-1ubuntu2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/status
```

I see this error on `f1937f69`, but once I went back to `d533719` it worked well.

**Comment by kwhrtsk** [comment]
In my test environment, Ubuntu 14.10 has the following version mongodb:

```
mongodb:
  Installed: 1:2.6.3-0ubuntu5
  Candidate: 1:2.6.3-0ubuntu5
  Version table:
 *** 1:2.6.3-0ubuntu5 0
        500 http://us.archive.ubuntu.com/ubuntu/ utopic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

I think that this may be compatibility problem between errbit and mongodb.
But I saw other error when I retried `f1937f69` in clean Ubuntu 14.10 environment.
Here is full operations executed on [this sample](https://github.com/kwhrtsk/chef-errbit-server/tree/master/sample):

```
vagrant up
./bin/knife zero bootstrap $VAGRANT_UBUNTU -N ubuntu.example -y
./bin/knife node run_list add ubuntu.example errbit-server
/bin/knife exec -E "nodes.all{|n| n.normal['errbit']['revision'] = 'f1937f6928cad3122fc9b90b066152cbaf9e692e'; n.save}"
./bin/knife zero converge 'hostname:*' -a knife_zero.host
```

Failed with this error:

```
192.168.33.11     ================================================================================
192.168.33.11     Error executing action `run` on resource 'execute[. /etc/profile.d/rbenv.sh && bundle install --path=/opt/errbit/shared/bundle]'
192.168.33.11     ================================================================================
192.168.33.11
192.168.33.11     Mixlib::ShellOut::ShellCommandFailed
192.168.33.11     ------------------------------------
192.168.33.11     Expected process to exit with [0], but received '7'
192.168.33.11     ---- Begin output of . /etc/profile.d/rbenv.sh && bundle install --path=/opt/errbit/shared/bundle ----
192.168.33.11     STDOUT: Fetching gem metadata from https://rubygems.org/............
192.168.33.11     Fetching version metadata from https://rubygems.org/...
192.168.33.11     Fetching dependency metadata from https://rubygems.org/..
192.168.33.11     Could not find mongoid-rspec-2.3.0.beta in any of the sources
192.168.33.11     STDERR: sh: 9: /etc/profile.d/rbenv.sh: source: not found
192.168.33.11     ---- End output of . /etc/profile.d/rbenv.sh && bundle install --path=/opt/errbit/shared/bundle ----
192.168.33.11     Ran . /etc/profile.d/rbenv.sh && bundle install --path=/opt/errbit/shared/bundle returned 7
192.168.33.11
192.168.33.11     Resource Declaration:
192.168.33.11     ---------------------
192.168.33.11     # In /var/chef/cache/cookbooks/errbit-server/recipes/app.rb
192.168.33.11
192.168.33.11      46:     execute ". /etc/profile.d/rbenv.sh && bundle install --path=#{new_resource.deploy_to}/shared/bundle" do
192.168.33.11      47:       environment({"RBENV_VERSION" => _ruby_version})
192.168.33.11      48:       cwd  release_path
192.168.33.11      49:       user _user
192.168.33.11      50:     end
192.168.33.11      51:
192.168.33.11
192.168.33.11     Compiled Resource:
192.168.33.11     ------------------
192.168.33.11     # Declared in /var/chef/cache/cookbooks/errbit-server/recipes/app.rb:46:in `block (2 levels) in from_file'
192.168.33.11
192.168.33.11     execute(". /etc/profile.d/rbenv.sh && bundle install --path=/opt/errbit/shared/bundle") do
192.168.33.11       action [:run]
192.168.33.11       retries 0
192.168.33.11       retry_delay 2
192.168.33.11       default_guard_interpreter :execute
192.168.33.11       command ". /etc/profile.d/rbenv.sh && bundle install --path=/opt/errbit/shared/bundle"
192.168.33.11       backup 5
192.168.33.11       cwd "/opt/errbit/releases/20150923150725"
192.168.33.11       environment {"RBENV_VERSION"=>"2.2.2"}
192.168.33.11       returns 0
192.168.33.11       user "errbit"
192.168.33.11       declared_type :execute
192.168.33.11       cookbook_name "errbit-server"
192.168.33.11     end
```

The message indicates that bundler failed to find gem in errbit's Gemfile.
Same error occurs in my Mac.
So, I guess `f1937f69` is corrupted revision.
`errbit` has been upgraded its rails version [about one month ago](https://github.com/errbit/errbit/commit/a5104f32a12b1d0a2cd93af65d869b7e995e457a).
I recommend to use more older revision or current stable version `v0.4.0`.

FYI, `d533719` is last revision before rails upgrading.

**Comment by JustinAiken** [comment]
I actually just updated my revision to https://github.com/errbit/errbit/commit/8a9822201f2a2e971340154c78d4f058e21932ff (doubled filename bug was driving me crazy), and no errors came back..

**Comment by kwhrtsk** [comment]
That sounds good. You found revision that works without errors and fits your use case?
I'd like to close this issue if your problem resolved.

**Comment by JustinAiken** [comment]
Sure, our errbit is humming away well... thanks for the great cookbook!
